apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: logistic-app
type: Opaque
stringData:
  DB_CONNECTION: "Host=POSTGRESQL_FQDN;Port=5432;Username=postgres;Password=DB_PASSWORD;SSL Mode=Require;"
  KAFKA_BOOTSTRAP_SERVERS: "kafka:9092"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: logistic-app
data:
  ASPNETCORE_ENVIRONMENT: "Production"